[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "3o6a7t8FwQQ2zgTVfhBGu9WH6bt2mVdiBsAPcmhd5YVq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
